"""new tables

Revision ID: 806dca422c3a
Revises: 
Create Date: 2022-03-16 15:13:00.362366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806dca422c3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
